name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Vim compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vim
        run: |
          sudo apt-get update
          sudo apt-get install -y vim
          vim --version

      - name: Test plugin loading
        run: vim -u NONE -c "source plugin/cmake-presets-vim.vim" -c "quit"

  cmake-preset:
    name: CMake preset test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vim
        run: |
          sudo apt-get update
          sudo apt-get install -y vim
          vim --version

      - name: Install CMake
        run: |
          sudo apt-get install -y cmake ninja-build
          cmake --version

      - name: run cmake preset test
        run: vim -V100 -u NONE --cmd 'source test/test-preset-detection.vim'
